// Auto-generated by Makefile Sun May 25 03:28:54 2025

#define PACKAGE "busybox-shims"
#define PACKAGE_NAME "Busybox Windows Shims"
#define VERSION "1.0.0"
#define VERSION_1 1
#define VERSION_2 0
#define VERSION_3 0
#define VERSION_4 1
#define BUILD_DATE "20250525"
#define BUILD_YEAR "2025"
#define BUILD_MONTH "05"
#define BUILD_MDAY "25"
#define BUILD_NUMBER "1"
