// Auto-generated by Makefile Sat May 24 23:37:33 2025

#define PACKAGE "busybox-shims"
#define PACKAGE_NAME "Busybox Windows Shims"
#define VERSION "0.1.0"
#define VERSION_1 0
#define VERSION_2 1
#define VERSION_3 0
#define VERSION_4 1
#define BUILD_DATE "20250524"
#define BUILD_YEAR "2025"
#define BUILD_MONTH "05"
#define BUILD_MDAY "24"
#define BUILD_NUMBER "1"
