name: build
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
           name: "Windows Latest MinGW32",
           os: windows-latest,
           toolchain: mingw32,
           packagelabel: busybox-shims-x86
          }
        - {
           name: "Windows Latest MinGW64",
           os: windows-latest,
           toolchain: mingw64,
           packagelabel: busybox-shims-x64
          }

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout submodules
      run: |
        git submodule update --init --recursive

    - name: MinGW64 setup
      if: startsWith(matrix.config.name, 'Windows Latest MinGW')
      shell: cmd
      run: |
        c:\msys64\usr\bin\pacman --noconfirm -S base-devel
        c:\msys64\usr\bin\pacman --noconfirm -S mingw-w64-x86_64-gcc
        c:\msys64\usr\bin\pacman --noconfirm -S mingw-w64-i686-gcc
        c:\msys64\usr\bin\pacman --noconfirm -S zip

    - name: Generate
      if: startsWith(matrix.config.name, 'Windows')
      shell: cmd
      run: |
        @if "${{ matrix.config.toolchain }}"=="mingw32" set PATH=c:\msys64\mingw32\bin;%PATH%
        @if "${{ matrix.config.toolchain }}"=="mingw64" set PATH=c:\msys64\mingw64\bin;%PATH%
        .\configure

    - name: Compile
      if: startsWith(matrix.config.name, 'Windows')
      shell: cmd
      run: |
        @if "${{ matrix.config.toolchain }}"=="mingw32" set PATH=c:\msys64\mingw32\bin;%PATH%
        @if "${{ matrix.config.toolchain }}"=="mingw64" set PATH=c:\msys64\mingw64\bin;%PATH%
        cd build
        mingw32-make all
        c:\msys64\usr\bin\zip ${{ matrix.config.packagelabel }}.zip *.exe

    - name: Package
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ matrix.config.toolchain }}
        path: build/*.exe

    - name: Release artifacts
      if: startsWith(matrix.config.name, 'Windows')
      uses: softprops/action-gh-release@v2
      with:
        files: ./build/${{ matrix.config.packagelabel }}.zip
        draft: true
